# ==============================================================================
# Authentication & User Management Service (Port 8081)
# ==============================================================================
server.port=8081
spring.application.name=AUTH-SERVICE

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/flight_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Initial Admin Seeding Configuration
app.seed.admin.enabled=true
app.seed.admin.email=admin@example.com
app.seed.admin.password=Password123
app.seed.admin.fullName=System Administrator
